# Generated by Django 3.0.3 on 2020-04-23 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30, null=True)),
                ('Workout_for', models.CharField(max_length=30, null=True)),
                ('no_of_workout', models.IntegerField(null=True)),
                ('no_of_set', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=30, null=True)),
                ('repeatation', models.CharField(max_length=30, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Workout')),
            ],
        ),
    ]
