# Generated by Django 3.0.3 on 2020-04-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200423_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'verbose_name_plural': 'Workout'},
        ),
    ]
