# Generated by Django 3.0.3 on 2020-06-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200423_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
    ]
