# Generated by Django 3.0.1 on 2019-12-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assigments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('task', models.CharField(max_length=100)),
            ],
        ),
    ]
