# Generated by Django 3.0.1 on 2020-01-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigments',
            name='topic',
            field=models.CharField(default='', max_length=50),
        ),
    ]
