# Generated by Django 3.0.1 on 2020-01-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_passwd',
            field=models.CharField(default='2606', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='t_passwd',
            field=models.CharField(default='2606', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
