# Generated by Django 3.0.1 on 2020-01-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_passwd',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='teacher',
            name='t_passwd',
            field=models.CharField(default='', max_length=300),
        ),
    ]
