# Generated by Django 3.0.1 on 2020-01-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200109_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='s_gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='t_cont',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='t_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='t_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tnr',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
