# Generated by Django 3.0.1 on 2020-01-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assigments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('que', models.CharField(max_length=100)),
                ('opt_a', models.CharField(max_length=50)),
                ('opt_b', models.CharField(max_length=50)),
                ('opt_c', models.CharField(max_length=50)),
                ('opt_d', models.CharField(max_length=50)),
                ('ans', models.CharField(max_length=50)),
                ('techer', models.CharField(max_length=50)),
            ],
        ),
    ]
