# Generated by Django 3.0.1 on 2020-01-11 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200111_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigments',
            name='date',
            field=models.DateField(default=datetime.date(2020, 1, 11)),
        ),
    ]
