# Generated by Django 3.0.1 on 2020-01-11 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200111_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateField()),
                ('a_duedate', models.DateField()),
                ('a_topic', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='assigments',
            name='date',
        ),
        migrations.RemoveField(
            model_name='assigments',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='assigments',
            name='topic',
        ),
        migrations.AddField(
            model_name='assigments',
            name='date_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.AssignmentDate'),
        ),
    ]
