# Generated by Django 3.0.1 on 2020-01-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200111_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigments',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assigments',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assigments',
            name='topic',
            field=models.CharField(default='', max_length=50),
        ),
    ]
