# Generated by Django 3.0.1 on 2020-01-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200111_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigments',
            name='date_id',
            field=models.IntegerField(null=True),
        ),
    ]
