# Generated by Django 3.0.1 on 2020-01-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='attemp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='correct',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
