# Generated by Django 3.0.1 on 2020-01-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20200117_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='attemp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='correct',
            field=models.IntegerField(null=True),
        ),
    ]
