# Generated by Django 3.0.1 on 2020-01-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20200117_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_pnr', models.IntegerField()),
                ('topic', models.CharField(default='', max_length=50)),
                ('attemp', models.IntegerField(null=True)),
                ('correct', models.IntegerField(null=True)),
            ],
        ),
    ]
