# Generated by Django 3.0.1 on 2020-01-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_solvedassignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedassignments',
            name='s_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
