# Generated by Django 3.0.1 on 2020-01-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_solvedassignments_s_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedassignments',
            name='s_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
